#Q1 -> LIST ALL FILES IN LONG LISTING (DETAILED) FORMAT

#Q2 -> DISPLAY PRESENT WORKING DIRECTORY

#Q3 -> CREATE DIRECTORY

#Q4 -> CREATE DIRECTORY

#Q5 -> REMOVE (DELETE) FILE

#Q6 -> REMOVE DIRECTORY AND ITS CONTENTS RECURSIVELY

#Q7 -> FORCE REMOVAL OF FILE WITHOUT PROMPTING FOR CONFIRMATION

#Q8 -> FOREFULLY REMOVE DIRECTORY RECURSIVELY

#Q9 -> COPY FILE1 TO FILE2

#Q10 -> COPY SOURCE_DIRECTORY RECURSIVELY TO DESTINATION

#Q11 -> RENAME OR MOVE FILE1 TO FILE2

#Q12 -> CREATE SYMBOLIC LINK TO LINKNAME

#Q13 -> CREATE EMPTY FILE OR UPDATE ACCESS AND MODIFICATION TIMES OF FILES

#Q14 -> VIEW CONTENTS OF FILE

#Q15 -> BROWSE THROUGH TEXT FILE

#Q16 -> DISPLAY FIRST 10 LINES OF FILE

#Q17 -> DISPLAY LAST 10 LINES OF FILE

#Q18 -> DISPLAY LAST 10 LINES OF FILE AND FOLLOW FILES AS IT GROWS



#Q16 ->
