#Q1->DISPLAY LINUX SYSTEM INFORMATION

#Q2->DISPLAY KERNEL RELEASE INFORMATION

#Q3->SHOW WHICH VERSION OF REDHAT INSTALLED

#Q4->SHOW HOW LONG SYSTEM HAS BEEN RUNNING PLUS LOAD

#Q5->SHOW SYSTEM HOST NAME

#Q6->DISPLAY IP ADDRESS OF HOST

#Q7->SHOW SYSTEM REBOOT HISTORY

#Q8->SHOW CURRENT DATE AND TIME

#Q9->SHOW THIS MONTH'S CALENDAR

#Q10->DISPLAY WHO'S ONLINE

#Q11->WHO YOU ARE LOGGED IN AS




